### ISSUE TITLE
Provide an example how to handle keys like <BS>

### ISSUE THREAD

**Issue by Arelav** [spinks/vim-leader-guide#10]
Provide an example how to handle keys like <BS>
```
<leader><BS> :nohlsearch<CR>
let g:lmap['<BS>'] = 'Turn of highlight for search results'
```
I think it's self explanatory. It took me a time to understand how to handle key names like `<BS>`

**Comment by spinks** [comment]
Closed with 7072356285caee37bc5b6922bd30aab581ffe68b.
