### ISSUE TITLE
Neovim 0.4.4 doesn't recoginze leaderGuide#register_prefix_descriptions

### ISSUE THREAD

**Issue by AchmadFathoni** [spinks/vim-leader-guide#11]
Every time I start my neovim with this config
```
let mapleader = "\<Space>"      
let g:lmap = {}        
let g:lmap.c = 'NERDCommenter'      
call leaderGuide#register_prefix_descriptions("<Space>", "g:lmap")      
nnoremap <silent> <leader> :<c-u>LeaderGuide '<Space>'<CR>      
vnoremap <silent> <leader> :<c-u>LeaderGuideVisual '<Space>'<CR> 

```
I got
`E117: Unknown function: leaderGuide#register_prefix_description`

**Comment by spinks** [comment]
To check have you got the plugin installed correctly, through vim-plug or otherwise.

If using plug you would need to make sure its included before you call the leaderGuide function.

**Comment by AchmadFathoni** [comment]
I install your plugin with usual `Plug 'spinks/vim-leader-guide'. Is there any extra step to include your plugin?

**Comment by spinks** [comment]
No that should be all. I'm unable to reproduce, the only other thing I can think of is have you run `:PlugInstall`?

**Comment by AchmadFathoni** [comment]
Thanks for the hint, after I put  `Plug 'spinks/vim-leader-guide'` above the `call leaderGuide#register_prefix_descriptions("<Space>", "g:lmap")` everything is working. Sorry to bother you. This is my first time encountering call in init.vim. I suggest you put a warning about this in the readme.md.
