### ISSUE TITLE
Configuration example using Lua?

### ISSUE THREAD

**Issue by Julpikar** [spinks/vim-leader-guide#6]
I have been trying to make this plugin configuration using lua, but simply not working. This is my configuration:
``` lua
local leader_map = {}
leader_map["lsp"] = {
  name = 'lsp'
}
api.nvim_set_keymap('n', '<LEADER>', ':<c-u>LeaderGuide \'<Space>\'<CR>', {silent = true})
api.nvim_set_keymap('v', '<LEADER>', ':<c-u>LeaderGuideVisual \'<Space>\'<CR>', {silent = true})

print(vim.inspect(leader_map))
vim.fn['leaderGuide#register_prefix_descriptions']("<Space>", leader_map)
```
This is my error screenshoot:
![image](https://user-images.githubusercontent.com/17688038/107782626-dc569980-6d7b-11eb-8515-e6cd93bf559d.png)

**Comment by spinks** [comment]
I do not have experience with Lua, so would have to look at this at some point in the future. If you manage to get it to work, feel free to share details.

**Comment by Julpikar** [comment]
Thanx for your response. There are PR https://github.com/neovim/neovim/pull/13823 for this issue.

**Comment by NTBBloodbath** [comment]
I recently changed my settings to Lua using `packer.nvim` as plugin manager, hope my settings for [this plugin](https://github.com/NTBBloodbath/nvlood/blob/main/nvim/lua/plugins/leader-mapper.lua) can help you :slightly_smiling_face:

I just used this from the Neovim API with Lua, and making a Lua dictionary and then assigning it to a Vim variable
- [vim.api.nvim_exec](https://github.com/nanotee/nvim-lua-guide#vimapinvim_exec)
- [vim.g](https://github.com/nanotee/nvim-lua-guide#using-meta-accessors-1)
