### ISSUE TITLE
Keyboard shortcuts list is empty on Neovim 0.4.3

### ISSUE THREAD

**Issue by andyrichardson** [spinks/vim-leader-guide#9]
Hey there, first off - thanks for taking the time to make this 🙌 

I've been keen to try it out but I'm having some issues getting it to display any shortcuts.

I don't think it's a config issue as [vim-which-key](https://github.com/liuchengxu/vim-which-key) is working fine with an almost identical config.

```vim
let g:lmap = {}
let g:lmap.t = 'test'
let g:lmap.l = {'name' : 'language'}
let g:lmap.l.p = 'prettier'

nnoremap <space> <Nop>
map <space> <leader>
imap jj <Esc>
nmap <leader>lp :CocCommand prettier.formatFile<CR>

call leaderGuide#register_prefix_descriptions("<space>", "g:lmap")
nnoremap <silent> <leader> :<c-u>LeaderGuide '<space>'<CR>
```

<details>
  <summary>Here is a gif of the issue</summary>

![Kapture 2021-03-21 at 13 07 27](https://user-images.githubusercontent.com/10779424/111906151-197f0d00-8a47-11eb-9d08-69b846059d3b.gif)

</details>

**Comment by spinks** [comment]
Just to check, have you got the leader-l-p and leader-t mappings assigned in vim (`nmap`, `map`, etc)? If it's not assigned it won't appear in the leader guide despite being in the dictionary.

This is the default behaviour at least, if you want to change this you check the `g:leaderGuide_mode_local_only` info in the readme.

**Comment by andyrichardson** [comment]
@spinks thanks for the response

I've updated the example above to include my mappings. 

In this case, some of the mappings do exist but still aren't presented.

Edit: I'm seeing different results when calling `:LeaderGuide <Space>` and `:LeaderGuide <space>` - is the space character case sensitive?

Edit2: Looks like [this is case sensitive](https://github.com/spinks/vim-leader-guide/blob/master/autoload/leaderGuide.vim#L8)

**Comment by spinks** [comment]
Re the case sensitivity - that shouldn't be an issue as that comparison `==?` is case insensitive.

I tested with your minimal config and found the same issue. Could you try setting the `mapleader` variable in vim with `let mapleader = "\<Space>"`, and see if this resolves the issue.

I think this may be needed as when `<leader>` mappings are parsed the `mapleader` variable needs to be equal to the key you pass to the register function.

**Comment by andyrichardson** [comment]
@spinks you hero - that's done the job 👍 

I'm guessing there's no way round the requirement for the variable so I'll close this!
